{
  "singleton_construct_error": "singleton クラス %(classname)s のインスタンスを作成できません",
  "create_local_item_error": "createLocalItem でエラーが発生しました: ",
  "error_filtering_remote_items": "listModifiedRemoteItemNames でリモート・アイテム・リストをフィルタリング中にエラーが発生しました",
  "push_error_creating_item": "アイテムの作成でプッシュ・エラーが発生しました: ",
  "push_error_updating_item": "アイテムの更新でプッシュ・エラーが発生しました: ",
  "pushed_item_error": "プッシュ済みアイテム・エラー: ",
  "invalid_path": "無効なパス: %(path)s",
  "timed_out_closing_read_stream": "読み取りストリームが閉じるのを待っているときにタイムアウトが発生しました",
  "remote_asset_not_found": "リモート・アセットが見つかりません: ",

  "deleted_original_file": "元のファイル %(old_name)s を削除しました。新規ファイル: %(new_name)s",
  "error_cancelling_job": "次のジョブのキャンセルでエラーが発生しました: ID %(id)s",
  "error_fs_get_item": "ファイル・システム getItem でエラーが発生しました",
  "error_parsing_item": "ファイル %(name)s のアイテムの構文解析でエラーが発生しました。%(message)s\n%(body)s",
  "get_items_error": "アイテム %(service_name)s の取得でエラーが発生しました:",
  "save_item_write_failed": "saveItem でファイル %(path)s への書き込みに失敗しました",
  "save_item_write_failed_bad_path": "saveItem でファイル %(path)s への書き込みに失敗しました。パスが正しくありません",
  "close_stream_failed": "closeStream がエラーで失敗しました: ",

  "name_required": "名前を指定する必要があります。",
  "category_exists": "名前 %(name)s のカテゴリーは既に存在します。",
  "template_required": "テンプレートを指定する必要があります。",
  "presentation_exists": "名前 %(name)s のプレゼンテーションは既に存在します。",
  "cannot_get_asset": "次のアセットを取得できません: %(path)s。状況コード: %(code)s",
  "deleted_asset": "次の ID のアセットを削除しました: %(id)s",
  "get_item_error": "アイテム %(service_name)s の取得でエラーが発生しました:",
  "create_item_error": "アイテム %(service_name)s の作成でエラーが発生しました:",
  "update_item_error": "アイテム %(service_name)s の更新でエラーが発生しました:",
  "delete_item_error": "アイテム %(service_name)s の削除でエラーが発生しました:",
  "error_tenant_map": "loadTenantMap でエラーが発生しました: ",
  "error_save_hashes": "saveHashes でエラーが発生しました: ",
  "error_update_hashes": "updateHashes でエラーが発生しました: ",
  "error_set_last_pull_timestamp": "setLastPullTimestamp でエラーが発生しました: ",
  "error_set_last_push_timestamp": "setLastPushTimestamp でエラーが発生しました: ",
  "error_get_hashes_for_file": "getHashesForFile でエラーが発生しました: ",

  "unknown_error": "不明なエラー",
  "service_unavailable": "IBM Watson Content Hub サービスは現在使用できません。",
  "service_error": "IBM Watson Content Hub サービスが技術的な問題を報告しています。",
  "service_response_error": "IBM Watson Content Hub サービスからエラー・コード %(code)d および次の状況メッセージが返されました: %(message)s",
  "operation_failed": "操作がエラーで失敗しました: ",
  "async_parallel_limit_error": "非同期の parallelLimit 呼び出しがエラーで失敗しました: ",
  "async_parallel_limit_results": "非同期 parallelLimit の結果: ",
  "please_try": "後で再試行してください。  問題が解決しない場合、お客様サポートにお問い合わせのうえ、%(log_dir)s にあるログ情報を提供してください",
  "conflict":"サービスでこの成果物の要求を処理中にエラーが発生し、エラー状態が返されました。"

}

